name: Testing

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0-dev.3268+9d4d96ca9

      - name: Test
        run: zig build test

      - name: Build
        run: |
          zig build
          zig build bind

  node:
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Run tests
        run: |
          pnpm install
          pnpm run test:node

  deno:
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.33.4

      - name: Run tests
        run: |
          deno run -A npm:esbuild packages/totp-wasm/index.ts --bundle --format=esm --platform=node --target=es2017 --minify --outfile=packages/totp-wasm/index.js
          deno test -A --import-map examples/deno/deno.json examples/deno/mod.ts
